### ISSUE TITLE
Micropython bin file

### ISSUE THREAD

**Issue by Guru-Solidz** [Mythologyli/MicroPython-ESP32-S3-N16R8#1]
Hi,
Thank you for the wonderful post.

Unfortunately, i am unable to build the firmware bin.

I am using ESP32S3N16R8 chip.  Would it be possible for you to share the bin file, so that I could use it to test the chip.

Thanks & Regards,
Guruprasad NK

**Comment by Mythologyli** [comment]
Hi, you can download the bin file here: https://github.com/Mythologyli/MicroPython-ESP32-S3-N16R8/releases

**Comment by Mythologyli** [comment]
You can also fork this repo and use Github Actions to build it.

**Comment by Guru-Solidz** [comment]
Hi Thanks for the super fast response!

my requirement is to get repl on esp32s3N16r8 on uart.  for that i followed the following process:
I am using raspberry pi running on raspbery pi os (buster)

#built requirements
sudo apt-get install git wget flex bison gperf python3 python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0

#allow current user read/write access to USB over serial port
sudo usermod -a -G dialout $USER

~/$ mkdir ~/esp
~/$ cd ~/esp

~/esp$ git clone --recursive -b v4.4-beta1 https://github.com/espressif/esp-idf.git
~/esp$ cd esp-idf
~/esp/esp-idf$ ./install.sh esp32s3
~/esp/esp-idf$ . ./export.sh
~/esp/esp-idf$ cd ..

~/esp$ mkdir mpy
~/esp$ cd mpy
~/esp/mpy$ git clone git://github.com/micropython/micropython --depth=1
~/esp/mpy$ cd ~/esp/mpy/micropython/ports/esp32/boards/

edit sdkconfig.spiram_sx
Change CONFIG_SPIRAM_MODE_QUAD=y -> CONFIG_SPIRAM_MODE_OCT=y

~/esp/mpy/micropython/ports/esp32/boards$ cd GENERIC_S3_SPIRAM/
edit mpconfigboard.cmake
comment out: boards/sdkconfig.usb -> # boards/sdkconfig.usb

~/esp/mpy/micropython/ports/esp32/boards/GENERIC_S3_SPIRAM$ cd ~/esp/mpy/micropython
~/esp/mpy/micropython$ make -C mpy-cross
~/esp/mpy/micropython$ cd ~/esp/mpy/micropython/ports/esp32/

edit Makefile
edit line: BOARD ?= GENERIC -> BOARD ?= GENERIC_S3_SPIRAM
edit line: idf.py $(IDFPY_FLAGS) build -> idf.py $(IDFPY_FLAGS) menuconfig

~/esp/mpy/micropython/ports/esp32$ make submodules
~/esp/mpy/micropython/ports/esp32$ make

but i am getting stuck at make.

since it didnt work out for me, i cloned and verified from your code, which is same as above, with the only difference being "edit mpconfigboard.cmake
comment out: boards/sdkconfig.usb -> # boards/sdkconfig.usb"

in both cases i am unsuccessful.

If you could help build a firmware bin which i could port, where i would be able to get repl on uart, it would resolve my issue.  the current idf version is 5 which is providing issues related to adc.

thanks & regards
Guruprasad NK

**Comment by Mythologyli** [comment]
The diffenerces between this repo and GENERIC_S3_SPIRAM are:

### GENERIC_S3_SPIRAM/sdkconfig.board

  CONFIG_ESPTOOLPY_FLASHSIZE_8MB=
  CONFIG_ESPTOOLPY_FLASHSIZE_16MB=y
  CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="partitions-16MiB.csv"

### sdkconfig.spiram_sx

  CONFIG_SPIRAM_MODE_OCT=y

You can edit the original GENERIC_S3_SPIRAM or follow my guide in README.md. And the firmware bin in release should work. If anything goes wrong, please post the error you're getting here.

**Comment by Guru-Solidz** [comment]
hi
i understood the differences and i used your repo for the same.

I modified mpconfigboard.cmake and commented out as shown below, as my
requirement is to get repl on uart.
comment out: boards/sdkconfig.usb -> # boards/sdkconfig.usb

when i come to "make", it throws out an error (if i use idf version5, it
says error in adc module, and if i use idf 4.4 the error is as follows:
File "/home/pi/esp/esp-idf/tools/idf_tools.py", line 1097, in
get_user_defined_targets
    if env == idf_env_json['idfSelectedId']:
KeyError: 'idfSelectedId'
*)*

If you could help provide me with micropython firmware (bin file) which i
could port to esp32n16r8, it would help a lot, as i have tried with
raspberry pi, and an ubuntu os based pc as well.
*_____________________________________________________________*
*Thanks*
*Guruprasad NK | *+91 98718 43210
Founder & CEO*  | **Solidz.IO*

**Comment by Mythologyli** [comment]
Hi, can you access the REPL on USB-UART using the firmware in release?

I think you want to access the REPL on UART, but I don't know why you commented out `boards/sdkconfig.usb` in `mpconfigboard.cmake`. `boards/sdkconfig.usb` just enables USB. The REPL is set by `#define MICROPY_HW_ENABLE_UART_REPL (1)` in `mpconfigboard.h`.

I have commented out `boards/sdkconfig.usb` and build the firmware. You can download it and test.
[firmware.zip](https://github.com/Mythologyli/MicroPython-ESP32-S3-N16R8/files/9943633/firmware.zip)

**Comment by Guru-Solidz** [comment]
Hi

You are really a God sent.

Thanks a ton.

The firmware works beautifully and I am able to access repl on uart.

thank you so much once again!  Very much appreciated and grateful!

*_____________________________________________________________*
*Thanks*
*Guruprasad NK | *+91 98718 43210
Founder & CEO*  | **Solidz.IO*
