### ISSUE TITLE
Upgrade to newer MicroPython say 1.21.0

### ISSUE THREAD

**Issue by geert56** [Mythologyli/MicroPython-ESP32-S3-N16R8#2]
Very nice piece of work. Your firmware works great on my cheap AliExpress ESP32-S3 N16R8 with UNO form factor.
How about upgrading to a newer MicroPython say 1.21.0? And providing the firmware as assets here on github.
Thank you.

I was able to build my own latest MicroPython firmware from scratch. Using esp-idf v5.0.4 and MicroPython 1.22.0.
I of course used your settings.

**Comment by Mythologyli** [comment]
I'm glad to hear that the repository has been helpful to you! Currently, I don't have an ESP32-S3 at hand to test. However, if you could submit a pull request with the changes you've made to upgrade to newest MicroPython, I'd greatly appreciate it.

**Comment by geert56** [comment]
The newer MicroPython versions already very well support SPIRAM and large flash. Their installation and build instructions are excellent. All I ended up doing was simply change the parameters for the flash size from 8MB to 16MB. No need for me to create a pull request here.
