### ISSUE TITLE
[ASK] About memory size

### ISSUE THREAD

**Issue by milen-prg** [Mythologyli/MicroPython-ESP32-S3-N16R8#3]
I'm beginner with esp. I have dev kit with ESP32 S3 N16R8. I use  your release 
firmware.zip 
and
esptool -p PORT -b 460800 --chip esp32s3 write_flash --flash_mode dio --flash_freq 80m 0x0 firmware.bin

Which was successful. But I have some strange results with reporting the memory sizes by the device Python in REPL:

`MicroPython 203dae4 on 2022-09-05; ESP32S3 module (spiram) with ESP32S3

Type "help()" for more information.

>>> import os
>>> s = os.statvfs('//')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 19] ENODEV
>>> s = os.statvfs('/')
>>> s
(0, 0, 0, 0, 0, 0, 0, 0, 0, 128)
>>> '{0} MB'.format((s[0]*s[3])/1048576)
'0.0 MB'
>>> import esp
>>> esp.flash_size()
16777216
>>> df()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'df' isn't defined
>>> `

Please, can you explain me if here all is OK and if this your software is the only way to use optimally my dev kit with Python?
Will be used all 16MB flash for my scripts (and can I write from scripts files with data)? Will this use all my 8MB PSRAM for RAM?
Or I must use any of these [https://micropython.org/download/ESP32_GENERIC_S3/](https://micropython.org/download/ESP32_GENERIC_S3/) will they use all 16MB/8MB. Are they newer?
Thank, you in advance!

**Comment by Mythologyli** [comment]
Hi, you can try this build: https://github.com/Mythologyli/MicroPython-ESP32-S3-N16R8/actions/runs/9222234486

**Comment by milen-prg** [comment]
This see 8MB PSRAM, excellent! But ONLY 8MB Flash! The Flash is 16MB and the old version given properly gc.mem_free(). Now:

`MicroPython df41913 on 2024-05-24; Generic ESP32S3 module with Octal-SPIRAM with ESP32S3

Type "help()" for more information.

>>> import os
>>> s = os.statvfs('//')
>>> s
(4096, 4096, 1536, 1533, 1533, 0, 0, 0, 0, 255)
>>> '{0} MB'.format((s[0]*s[3])/1048576)
'5.988281 MB'
>>> import esp
>>> esp.flash_size()
8388608
>>> import gc
>>> gc.mem_free()
8299616`

Thank, you for fast support! If correct also the flash size and all other works, this will be the only working version of Python for this kits, because I tried also Circuit python special version, which do not work at all.

**Comment by Mythologyli** [comment]
Oops! I made a mistake about the config file path. This build should work: https://github.com/Mythologyli/MicroPython-ESP32-S3-N16R8/actions/runs/9222739272

**Comment by milen-prg** [comment]
Oh, thank, you, very, very much!!!
All works:

`MicroPython df41913 on 2024-05-24; Generic ESP32S3 module with Octal-SPIRAM with ESP32S3

Type "help()" for more information.

>>> import os
>>> s = os.statvfs('//')
>>> s
(4096, 4096, 3584, 3581, 3581, 0, 0, 0, 0, 255)
>>> '{0} MB'.format((s[0]*s[3])/1048576)
'13.98828 MB'
>>> import esp
>>> esp.flash_size()
16777216
>>> import gc
>>> gc.mem_free()
8299616`

At least I can start to experiment with this kit and MicroPython.
For example I tried:

a = [0]*300000
which works immediately.

Strange is that after that the command:
gc.mem_free()
used about 1 minute to return:
6194832

But this maybe is normal. Thank, you again for the fast support!
